In [1]:
import pandas as pd

df = pd.read_csv('../data/train_ship_segmentations_v2.csv')
df

              ImageId                                      EncodedPixels
0       00003e153.jpg                                                NaN
1       0001124c7.jpg                                                NaN
2       000155de5.jpg  264661 17 265429 33 266197 33 266965 33 267733...
3       000194a2d.jpg  360486 1 361252 4 362019 5 362785 8 363552 10 ...
4       000194a2d.jpg  51834 9 52602 9 53370 9 54138 9 54906 9 55674 ...
...               ...                                                ...
231718  fffedbb6b.jpg                                                NaN
231719  ffff2aa57.jpg                                                NaN
231720  ffff6e525.jpg                                                NaN
231721  ffffc50b4.jpg                                                NaN
231722  ffffe97f3.jpg                                                NaN

[231723 rows x 2 columns]

In [2]:
df['EncodedPixels'] = df['EncodedPixels'].fillna('')
df

              ImageId                                      EncodedPixels
0       00003e153.jpg
1       0001124c7.jpg
2       000155de5.jpg  264661 17 265429 33 266197 33 266965 33 267733...
3       000194a2d.jpg  360486 1 361252 4 362019 5 362785 8 363552 10 ...
4       000194a2d.jpg  51834 9 52602 9 53370 9 54138 9 54906 9 55674 ...
...               ...                                                ...
231718  fffedbb6b.jpg
231719  ffff2aa57.jpg
231720  ffff6e525.jpg
231721  ffffc50b4.jpg
231722  ffffe97f3.jpg

[231723 rows x 2 columns]

In [4]:
df.head(50)

          ImageId                                      EncodedPixels
0   00003e153.jpg
1   0001124c7.jpg
2   000155de5.jpg  264661 17 265429 33 266197 33 266965 33 267733...
3   000194a2d.jpg  360486 1 361252 4 362019 5 362785 8 363552 10 ...
4   000194a2d.jpg  51834 9 52602 9 53370 9 54138 9 54906 9 55674 ...
5   000194a2d.jpg  198320 10 199088 10 199856 10 200624 10 201392...
6   000194a2d.jpg  55683 1 56451 1 57219 1 57987 1 58755 1 59523 ...
7   000194a2d.jpg  254389 9 255157 17 255925 17 256693 17 257461 ...
8   0001b1832.jpg
9   00021ddc3.jpg  108287 1 109054 3 109821 4 110588 5 111356 5 1...
10  00021ddc3.jpg  101361 1 102128 3 102896 4 103663 6 104430 9 1...
11  00021ddc3.jpg  74441 3 75207 5 75975 5 76743 5 77511 5 78280 ...
12  00021ddc3.jpg  74444 4 75212 4 75980 4 76748 4 77517 3 78285 ...
13  00021ddc3.jpg  150423 2 151190 3 151958 3 152726 4 153495 3 1...
14  00021ddc3.jpg  139644 2 140408 6 141174 9 141942 9 142711 6 1...
15  00021ddc3.jpg  75972 3 76738 5 77506 5 78274 5 79042 6 79811 ...
16  00021ddc3.jpg  86727 2 87493 4 88261 4 89030 3 89798 4 90566 ...
17  00021ddc3.jpg  95225 2 95992 5 96760 7 97527 9 98294 9 99062 ...
18  0002756f7.jpg  255784 2 256552 4 257319 7 258087 9 258854 12 ...
19  0002756f7.jpg  248878 1 249645 4 250413 6 251180 9 251948 10 ...
20  0002d0f32.jpg
21  000303d4d.jpg
22  00031f145.jpg  340363 1 341129 4 341896 6 342663 7 343429 10 ...
23  00052ed46.jpg
24  000532683.jpg  458957 14 459725 14 460493 14 461261 14 462029...
25  000532683.jpg  567543 2 568309 4 569077 5 569846 4 570614 5 5...
26  00053c6ba.jpg  565382 3 566144 9 566909 12 567677 13 568445 1...
27  00057a50d.jpg
28  000592296.jpg
29  0005d01c8.jpg  56010 1 56777 3 57544 6 58312 7 59079 9 59846 ...
30  0005d01c8.jpg  365871 1 366638 3 367405 6 368173 7 368940 9 3...
31  0005d6d95.jpg  265143 1 265910 4 266678 5 267445 7 268212 10 ...
32  0006c52e8.jpg  146366 1 147132 4 147899 5 148666 7 149432 10 ...
33  0007b8229.jpg
34  000805313.jpg
35  000811bb6.jpg
36  0008d6216.jpg
37  000913daf.jpg
38  000952d51.jpg
39  000969125.jpg
40  0009a46e1.jpg
41  000a4d4fd.jpg
42  000aed819.jpg
43  000baef0c.jpg
44  000bd9ac4.jpg
45  000c150b0.jpg
46  000c34352.jpg
47  000d26c17.jpg
48  000d42241.jpg  369226 3 369992 5 370760 5 371528 5 372296 5 3...
49  000db3e62.jpg

In [4]:
df = df.groupby('ImageId')['EncodedPixels'].agg(list).reset_index()
df

              ImageId                                      EncodedPixels
0       00003e153.jpg                                                 []
1       0001124c7.jpg                                                 []
2       000155de5.jpg  [264661 17 265429 33 266197 33 266965 33 26773...
3       000194a2d.jpg  [360486 1 361252 4 362019 5 362785 8 363552 10...
4       0001b1832.jpg                                                 []
...               ...                                                ...
192551  fffedbb6b.jpg                                                 []
192552  ffff2aa57.jpg                                                 []
192553  ffff6e525.jpg                                                 []
192554  ffffc50b4.jpg                                                 []
192555  ffffe97f3.jpg                                                 []

[192556 rows x 2 columns]

In [7]:
idx = 3
rles = df['EncodedPixels'][idx]

for rle in rles:
    print(rle)

print(len(rles))

360486 1 361252 4 362019 5 362785 8 363552 10 364321 10 365090 9 365858 10 366627 10 367396 9 368165 9 368933 10 369702 10 370471 9 371240 9 372009 9 372777 10 373546 9 374315 9 375084 7 375852 6 376621 3 377390 1
51834 9 52602 9 53370 9 54138 9 54906 9 55674 7 56442 7 57210 7 57978 7 58746 7 59514 7 60282 7 61050 9 61818 9 62586 9 63354 9 64122 9 64890 9
198320 10 199088 10 199856 10 200624 10 201392 10 202160 10 202928 10 203696 10 204464 10 205232 10 206000 10 206768 10 207536 10 208304 10 209072 10 209840 10 210608 10 211376 10 212144 10 212912 10 213680 10 214448 10 215216 10 215984 10 216751 10 217519 10 218287 10 219055 10 219823 10 220591 10 221359 10 222127 10 222895 10 223663 10 224431 10 225199 10 225967 10 226735 10 227503 10 228271 10 229039 10 229807 10 230575 10 231343 10 232111 10 232879 10 233647 10 234415 10
55683 1 56451 1 57219 1 57987 1 58755 1 59523 1 60291 1
254389 9 255157 17 255925 17 256693 17 257461 17 258229 17 258997 17 259765 17 260533 17 261301 17 262068 18 262836 17 263604 17 264372 17 265140 17 265908 17 266676 17 267444 17 268212 17 268980 17 269748 17 270516 17 271284 17 272052 17 272820 17 273588 17 274356 17 275124 17 275891 18 276659 17 277427 17 278195 17 278963 17 279731 17 280499 17 281267 17 282035 17 282803 17 283580 8
5